import "../globals.css";
import { Inter } from "next/font/google";
import Sidebar from "../../components/Sidebar/Index";
import InnerHeader from "../../components/InnerHeader/Index";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="dark:bg-boxdark-2 dark:text-bodydark sidebar-bg">
      <div className="flex h-screen overflow-hidden">
        <Sidebar />
        <div className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden">
          <InnerHeader />
          <main>
            {children}
          </main>
        </div>
      </div>
    </div>
  );
}
